# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ContactDeviceAdd(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, device_label=None, escalation_notification_sound=None, chat_escalation_sound=None, resolved_notification_sound=None):
        """
        ContactDeviceAdd - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'device_label': 'str',
            'escalation_notification_sound': 'str',
            'chat_escalation_sound': 'str',
            'resolved_notification_sound': 'str'
        }

        self.attribute_map = {
            'device_label': 'device_label',
            'escalation_notification_sound': 'escalation_notification_sound',
            'chat_escalation_sound': 'chat_escalation_sound',
            'resolved_notification_sound': 'resolved_notification_sound'
        }

        self._device_label = device_label
        self._escalation_notification_sound = escalation_notification_sound
        self._chat_escalation_sound = chat_escalation_sound
        self._resolved_notification_sound = resolved_notification_sound

    @property
    def device_label(self):
        """
        Gets the device_label of this ContactDeviceAdd.

        :return: The device_label of this ContactDeviceAdd.
        :rtype: str
        """
        return self._device_label

    @device_label.setter
    def device_label(self, device_label):
        """
        Sets the device_label of this ContactDeviceAdd.

        :param device_label: The device_label of this ContactDeviceAdd.
        :type: str
        """

        self._device_label = device_label

    @property
    def escalation_notification_sound(self):
        """
        Gets the escalation_notification_sound of this ContactDeviceAdd.

        :return: The escalation_notification_sound of this ContactDeviceAdd.
        :rtype: str
        """
        return self._escalation_notification_sound

    @escalation_notification_sound.setter
    def escalation_notification_sound(self, escalation_notification_sound):
        """
        Sets the escalation_notification_sound of this ContactDeviceAdd.

        :param escalation_notification_sound: The escalation_notification_sound of this ContactDeviceAdd.
        :type: str
        """

        self._escalation_notification_sound = escalation_notification_sound

    @property
    def chat_escalation_sound(self):
        """
        Gets the chat_escalation_sound of this ContactDeviceAdd.

        :return: The chat_escalation_sound of this ContactDeviceAdd.
        :rtype: str
        """
        return self._chat_escalation_sound

    @chat_escalation_sound.setter
    def chat_escalation_sound(self, chat_escalation_sound):
        """
        Sets the chat_escalation_sound of this ContactDeviceAdd.

        :param chat_escalation_sound: The chat_escalation_sound of this ContactDeviceAdd.
        :type: str
        """

        self._chat_escalation_sound = chat_escalation_sound

    @property
    def resolved_notification_sound(self):
        """
        Gets the resolved_notification_sound of this ContactDeviceAdd.

        :return: The resolved_notification_sound of this ContactDeviceAdd.
        :rtype: str
        """
        return self._resolved_notification_sound

    @resolved_notification_sound.setter
    def resolved_notification_sound(self, resolved_notification_sound):
        """
        Sets the resolved_notification_sound of this ContactDeviceAdd.

        :param resolved_notification_sound: The resolved_notification_sound of this ContactDeviceAdd.
        :type: str
        """

        self._resolved_notification_sound = resolved_notification_sound

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ContactDeviceAdd):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
