# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class OnCallAndOverrides(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, team=None, schedule=None, overrides=None):
        """
        OnCallAndOverrides - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'team': 'str',
            'schedule': 'list[TeamScheduleResource]',
            'overrides': 'list[TeamScheduleOverlayResource]'
        }

        self.attribute_map = {
            'team': 'team',
            'schedule': 'schedule',
            'overrides': 'overrides'
        }

        self._team = team
        self._schedule = schedule
        self._overrides = overrides

    @property
    def team(self):
        """
        Gets the team of this OnCallAndOverrides.

        :return: The team of this OnCallAndOverrides.
        :rtype: str
        """
        return self._team

    @team.setter
    def team(self, team):
        """
        Sets the team of this OnCallAndOverrides.

        :param team: The team of this OnCallAndOverrides.
        :type: str
        """

        self._team = team

    @property
    def schedule(self):
        """
        Gets the schedule of this OnCallAndOverrides.

        :return: The schedule of this OnCallAndOverrides.
        :rtype: list[TeamScheduleResource]
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """
        Sets the schedule of this OnCallAndOverrides.

        :param schedule: The schedule of this OnCallAndOverrides.
        :type: list[TeamScheduleResource]
        """

        self._schedule = schedule

    @property
    def overrides(self):
        """
        Gets the overrides of this OnCallAndOverrides.

        :return: The overrides of this OnCallAndOverrides.
        :rtype: list[TeamScheduleOverlayResource]
        """
        return self._overrides

    @overrides.setter
    def overrides(self, overrides):
        """
        Sets the overrides of this OnCallAndOverrides.

        :param overrides: The overrides of this OnCallAndOverrides.
        :type: list[TeamScheduleOverlayResource]
        """

        self._overrides = overrides

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, OnCallAndOverrides):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
