# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class OnCallInterval(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, true=None, false=None, duration=None):
        """
        OnCallInterval - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'true': 'str',
            'false': 'str',
            'duration': 'UserLogTotal'
        }

        self.attribute_map = {
            'true': 'true',
            'false': 'false',
            'duration': 'duration'
        }

        self._true = true
        self._false = false
        self._duration = duration

    @property
    def true(self):
        """
        Gets the true of this OnCallInterval.

        :return: The true of this OnCallInterval.
        :rtype: str
        """
        return self._true

    @true.setter
    def true(self, true):
        """
        Sets the true of this OnCallInterval.

        :param true: The true of this OnCallInterval.
        :type: str
        """

        self._true = true

    @property
    def false(self):
        """
        Gets the false of this OnCallInterval.

        :return: The false of this OnCallInterval.
        :rtype: str
        """
        return self._false

    @false.setter
    def false(self, false):
        """
        Sets the false of this OnCallInterval.

        :param false: The false of this OnCallInterval.
        :type: str
        """

        self._false = false

    @property
    def duration(self):
        """
        Gets the duration of this OnCallInterval.

        :return: The duration of this OnCallInterval.
        :rtype: UserLogTotal
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """
        Sets the duration of this OnCallInterval.

        :param duration: The duration of this OnCallInterval.
        :type: UserLogTotal
        """

        self._duration = duration

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, OnCallInterval):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
