# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class OnCallLog(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, team_slug=None, start=None, end=None, user_logs=None):
        """
        OnCallLog - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'team_slug': 'str',
            'start': 'datetime',
            'end': 'datetime',
            'user_logs': 'list[UserLog]'
        }

        self.attribute_map = {
            'team_slug': 'teamSlug',
            'start': 'start',
            'end': 'end',
            'user_logs': 'userLogs'
        }

        self._team_slug = team_slug
        self._start = start
        self._end = end
        self._user_logs = user_logs

    @property
    def team_slug(self):
        """
        Gets the team_slug of this OnCallLog.

        :return: The team_slug of this OnCallLog.
        :rtype: str
        """
        return self._team_slug

    @team_slug.setter
    def team_slug(self, team_slug):
        """
        Sets the team_slug of this OnCallLog.

        :param team_slug: The team_slug of this OnCallLog.
        :type: str
        """

        self._team_slug = team_slug

    @property
    def start(self):
        """
        Gets the start of this OnCallLog.

        :return: The start of this OnCallLog.
        :rtype: datetime
        """
        return self._start

    @start.setter
    def start(self, start):
        """
        Sets the start of this OnCallLog.

        :param start: The start of this OnCallLog.
        :type: datetime
        """

        self._start = start

    @property
    def end(self):
        """
        Gets the end of this OnCallLog.

        :return: The end of this OnCallLog.
        :rtype: datetime
        """
        return self._end

    @end.setter
    def end(self, end):
        """
        Sets the end of this OnCallLog.

        :param end: The end of this OnCallLog.
        :type: datetime
        """

        self._end = end

    @property
    def user_logs(self):
        """
        Gets the user_logs of this OnCallLog.

        :return: The user_logs of this OnCallLog.
        :rtype: list[UserLog]
        """
        return self._user_logs

    @user_logs.setter
    def user_logs(self, user_logs):
        """
        Sets the user_logs of this OnCallLog.

        :param user_logs: The user_logs of this OnCallLog.
        :type: list[UserLog]
        """

        self._user_logs = user_logs

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, OnCallLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
