# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TeamScheduleOverlayResource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, orig=None, over=None, start=None, end=None):
        """
        TeamScheduleOverlayResource - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'orig': 'str',
            'over': 'str',
            'start': 'float',
            'end': 'float'
        }

        self.attribute_map = {
            'orig': 'orig',
            'over': 'over',
            'start': 'start',
            'end': 'end'
        }

        self._orig = orig
        self._over = over
        self._start = start
        self._end = end

    @property
    def orig(self):
        """
        Gets the orig of this TeamScheduleOverlayResource.
        The user scheduled on call (if any)

        :return: The orig of this TeamScheduleOverlayResource.
        :rtype: str
        """
        return self._orig

    @orig.setter
    def orig(self, orig):
        """
        Sets the orig of this TeamScheduleOverlayResource.
        The user scheduled on call (if any)

        :param orig: The orig of this TeamScheduleOverlayResource.
        :type: str
        """

        self._orig = orig

    @property
    def over(self):
        """
        Gets the over of this TeamScheduleOverlayResource.
        The user overriding the scheduled on call user (if any)

        :return: The over of this TeamScheduleOverlayResource.
        :rtype: str
        """
        return self._over

    @over.setter
    def over(self, over):
        """
        Sets the over of this TeamScheduleOverlayResource.
        The user overriding the scheduled on call user (if any)

        :param over: The over of this TeamScheduleOverlayResource.
        :type: str
        """

        self._over = over

    @property
    def start(self):
        """
        Gets the start of this TeamScheduleOverlayResource.
        The time the override is scheduled to start

        :return: The start of this TeamScheduleOverlayResource.
        :rtype: float
        """
        return self._start

    @start.setter
    def start(self, start):
        """
        Sets the start of this TeamScheduleOverlayResource.
        The time the override is scheduled to start

        :param start: The start of this TeamScheduleOverlayResource.
        :type: float
        """

        self._start = start

    @property
    def end(self):
        """
        Gets the end of this TeamScheduleOverlayResource.
        The time the override is scheduled to end

        :return: The end of this TeamScheduleOverlayResource.
        :rtype: float
        """
        return self._end

    @end.setter
    def end(self, end):
        """
        Sets the end of this TeamScheduleOverlayResource.
        The time the override is scheduled to end

        :param end: The end of this TeamScheduleOverlayResource.
        :type: float
        """

        self._end = end

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TeamScheduleOverlayResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
