# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UserLog(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, user_id=None, total=None, adjusted_total=None, log=None):
        """
        UserLog - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'user_id': 'str',
            'total': 'UserLogTotal',
            'adjusted_total': 'UserLogTotal',
            'log': 'list[OnCallInterval]'
        }

        self.attribute_map = {
            'user_id': 'userId',
            'total': 'total',
            'adjusted_total': 'adjustedTotal',
            'log': 'log'
        }

        self._user_id = user_id
        self._total = total
        self._adjusted_total = adjusted_total
        self._log = log

    @property
    def user_id(self):
        """
        Gets the user_id of this UserLog.

        :return: The user_id of this UserLog.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """
        Sets the user_id of this UserLog.

        :param user_id: The user_id of this UserLog.
        :type: str
        """

        self._user_id = user_id

    @property
    def total(self):
        """
        Gets the total of this UserLog.

        :return: The total of this UserLog.
        :rtype: UserLogTotal
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this UserLog.

        :param total: The total of this UserLog.
        :type: UserLogTotal
        """

        self._total = total

    @property
    def adjusted_total(self):
        """
        Gets the adjusted_total of this UserLog.

        :return: The adjusted_total of this UserLog.
        :rtype: UserLogTotal
        """
        return self._adjusted_total

    @adjusted_total.setter
    def adjusted_total(self, adjusted_total):
        """
        Sets the adjusted_total of this UserLog.

        :param adjusted_total: The adjusted_total of this UserLog.
        :type: UserLogTotal
        """

        self._adjusted_total = adjusted_total

    @property
    def log(self):
        """
        Gets the log of this UserLog.

        :return: The log of this UserLog.
        :rtype: list[OnCallInterval]
        """
        return self._log

    @log.setter
    def log(self, log):
        """
        Sets the log of this UserLog.

        :param log: The log of this UserLog.
        :type: list[OnCallInterval]
        """

        self._log = log

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UserLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
