# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class UserContact(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, device_type=None, label=None, ext_id=None, self_url=None):
        """
        UserContact - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'device_type': 'str',
            'label': 'str',
            'ext_id': 'str',
            'self_url': 'str'
        }

        self.attribute_map = {
            'device_type': 'deviceType',
            'label': 'label',
            'ext_id': 'extId',
            'self_url': '_selfUrl'
        }

        self._device_type = device_type
        self._label = label
        self._ext_id = ext_id
        self._self_url = self_url

    @property
    def device_type(self):
        """
        Gets the device_type of this UserContact.

        :return: The device_type of this UserContact.
        :rtype: str
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type):
        """
        Sets the device_type of this UserContact.

        :param device_type: The device_type of this UserContact.
        :type: str
        """

        self._device_type = device_type

    @property
    def label(self):
        """
        Gets the label of this UserContact.

        :return: The label of this UserContact.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this UserContact.

        :param label: The label of this UserContact.
        :type: str
        """

        self._label = label

    @property
    def ext_id(self):
        """
        Gets the ext_id of this UserContact.

        :return: The ext_id of this UserContact.
        :rtype: str
        """
        return self._ext_id

    @ext_id.setter
    def ext_id(self, ext_id):
        """
        Sets the ext_id of this UserContact.

        :param ext_id: The ext_id of this UserContact.
        :type: str
        """

        self._ext_id = ext_id

    @property
    def self_url(self):
        """
        Gets the self_url of this UserContact.

        :return: The self_url of this UserContact.
        :rtype: str
        """
        return self._self_url

    @self_url.setter
    def self_url(self, self_url):
        """
        Sets the self_url of this UserContact.

        :param self_url: The self_url of this UserContact.
        :type: str
        """

        self._self_url = self_url

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, UserContact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
