# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import victorops_client
from victorops_client.rest import ApiException
from victorops_client.apis.teams_api import TeamsApi


class TestTeamsApi(unittest.TestCase):
    """ TeamsApi unit test stubs """

    def setUp(self):
        self.api = victorops_client.apis.teams_api.TeamsApi()

    def tearDown(self):
        pass

    def test_team_get(self):
        """
        Test case for team_get

        List teams
        """
        pass

    def test_team_post(self):
        """
        Test case for team_post

        Add a team
        """
        pass

    def test_team_team_delete(self):
        """
        Test case for team_team_delete

        Remove a team
        """
        pass

    def test_team_team_get(self):
        """
        Test case for team_team_get

        Retrieve information for a team
        """
        pass

    def test_team_team_members_get(self):
        """
        Test case for team_team_members_get

        Retrieve a list of members for a team
        """
        pass

    def test_team_team_members_post(self):
        """
        Test case for team_team_members_post

        Add a team member
        """
        pass

    def test_team_team_members_user_delete(self):
        """
        Test case for team_team_members_user_delete

        Remove a team member
        """
        pass

    def test_team_team_put(self):
        """
        Test case for team_team_put

        Update a team
        """
        pass


if __name__ == '__main__':
    unittest.main()
