# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import victorops_client
from victorops_client.rest import ApiException
from victorops_client.apis.incidents_api import IncidentsApi


class TestIncidentsApi(unittest.TestCase):
    """ IncidentsApi unit test stubs """

    def setUp(self):
        self.api = victorops_client.apis.incidents_api.IncidentsApi()

    def tearDown(self):
        pass

    def test_incidents_ack_patch(self):
        """
        Test case for incidents_ack_patch

        Acknowledge an incident or list of incidents
        """
        pass

    def test_incidents_by_user_ack_patch(self):
        """
        Test case for incidents_by_user_ack_patch

        Acknowledge all incidents for which a user was paged.
        """
        pass

    def test_incidents_by_user_resolve_patch(self):
        """
        Test case for incidents_by_user_resolve_patch

        Resolve all incidents for which a user was paged.
        """
        pass

    def test_incidents_get(self):
        """
        Test case for incidents_get

        Get current incident information
        """
        pass

    def test_incidents_post(self):
        """
        Test case for incidents_post

        Create a new incident
        """
        pass

    def test_incidents_resolve_patch(self):
        """
        Test case for incidents_resolve_patch

        Resolve an incident or list of incidents
        """
        pass


if __name__ == '__main__':
    unittest.main()
