# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import victorops_client
from victorops_client.rest import ApiException
from victorops_client.apis.oncall_api import OncallApi


class TestOncallApi(unittest.TestCase):
    """ OncallApi unit test stubs """

    def setUp(self):
        self.api = victorops_client.apis.oncall_api.OncallApi()

    def tearDown(self):
        pass

    def test_team_team_oncall_schedule_get(self):
        """
        Test case for team_team_oncall_schedule_get

        Get a team's on-call schedule
        """
        pass

    def test_team_team_oncall_user_patch(self):
        """
        Test case for team_team_oncall_user_patch

        Create an on-call override (take on-call)
        """
        pass

    def test_user_user_oncall_schedule_get(self):
        """
        Test case for user_user_oncall_schedule_get

        Get a user's on-call schedule
        """
        pass


if __name__ == '__main__':
    unittest.main()
