# coding: utf-8

"""
    VictorOps API

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class TeamsApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def team_get(self, x_vo_api_id, x_vo_api_key, **kwargs):
        """
        List teams
        Get a list of teams for your organization.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_get(x_vo_api_id, x_vo_api_key, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :return: ListTeamResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.team_get_with_http_info(x_vo_api_id, x_vo_api_key, **kwargs)
        else:
            (data) = self.team_get_with_http_info(x_vo_api_id, x_vo_api_key, **kwargs)
            return data

    def team_get_with_http_info(self, x_vo_api_id, x_vo_api_key, **kwargs):
        """
        List teams
        Get a list of teams for your organization.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_get_with_http_info(x_vo_api_id, x_vo_api_key, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :return: ListTeamResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_vo_api_id', 'x_vo_api_key']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method team_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_vo_api_id' is set
        if ('x_vo_api_id' not in params) or (params['x_vo_api_id'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_id` when calling `team_get`")
        # verify the required parameter 'x_vo_api_key' is set
        if ('x_vo_api_key' not in params) or (params['x_vo_api_key'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_key` when calling `team_get`")


        collection_formats = {}

        resource_path = '/team'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}
        if 'x_vo_api_id' in params:
            header_params['X-VO-Api-Id'] = params['x_vo_api_id']
        if 'x_vo_api_key' in params:
            header_params['X-VO-Api-Key'] = params['x_vo_api_key']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ListTeamResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def team_post(self, x_vo_api_id, x_vo_api_key, body, **kwargs):
        """
        Add a team
        Add a team to your organization.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_post(x_vo_api_id, x_vo_api_key, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param AddTeamPayload body: The team information (required)
        :return: AddTeamResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.team_post_with_http_info(x_vo_api_id, x_vo_api_key, body, **kwargs)
        else:
            (data) = self.team_post_with_http_info(x_vo_api_id, x_vo_api_key, body, **kwargs)
            return data

    def team_post_with_http_info(self, x_vo_api_id, x_vo_api_key, body, **kwargs):
        """
        Add a team
        Add a team to your organization.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_post_with_http_info(x_vo_api_id, x_vo_api_key, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param AddTeamPayload body: The team information (required)
        :return: AddTeamResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_vo_api_id', 'x_vo_api_key', 'body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method team_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_vo_api_id' is set
        if ('x_vo_api_id' not in params) or (params['x_vo_api_id'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_id` when calling `team_post`")
        # verify the required parameter 'x_vo_api_key' is set
        if ('x_vo_api_key' not in params) or (params['x_vo_api_key'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_key` when calling `team_post`")
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `team_post`")


        collection_formats = {}

        resource_path = '/team'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}
        if 'x_vo_api_id' in params:
            header_params['X-VO-Api-Id'] = params['x_vo_api_id']
        if 'x_vo_api_key' in params:
            header_params['X-VO-Api-Key'] = params['x_vo_api_key']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='AddTeamResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def team_team_delete(self, x_vo_api_id, x_vo_api_key, team, **kwargs):
        """
        Remove a team
        Remove a team from your organization.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_delete(x_vo_api_id, x_vo_api_key, team, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to be deleted (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.team_team_delete_with_http_info(x_vo_api_id, x_vo_api_key, team, **kwargs)
        else:
            (data) = self.team_team_delete_with_http_info(x_vo_api_id, x_vo_api_key, team, **kwargs)
            return data

    def team_team_delete_with_http_info(self, x_vo_api_id, x_vo_api_key, team, **kwargs):
        """
        Remove a team
        Remove a team from your organization.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_delete_with_http_info(x_vo_api_id, x_vo_api_key, team, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to be deleted (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_vo_api_id', 'x_vo_api_key', 'team']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method team_team_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_vo_api_id' is set
        if ('x_vo_api_id' not in params) or (params['x_vo_api_id'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_id` when calling `team_team_delete`")
        # verify the required parameter 'x_vo_api_key' is set
        if ('x_vo_api_key' not in params) or (params['x_vo_api_key'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_key` when calling `team_team_delete`")
        # verify the required parameter 'team' is set
        if ('team' not in params) or (params['team'] is None):
            raise ValueError("Missing the required parameter `team` when calling `team_team_delete`")


        collection_formats = {}

        resource_path = '/team/{team}'.replace('{format}', 'json')
        path_params = {}
        if 'team' in params:
            path_params['team'] = params['team']

        query_params = {}

        header_params = {}
        if 'x_vo_api_id' in params:
            header_params['X-VO-Api-Id'] = params['x_vo_api_id']
        if 'x_vo_api_key' in params:
            header_params['X-VO-Api-Key'] = params['x_vo_api_key']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def team_team_get(self, x_vo_api_id, x_vo_api_key, team, **kwargs):
        """
        Retrieve information for a team
        Get the information for the specified team.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_get(x_vo_api_id, x_vo_api_key, team, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to fetch (required)
        :return: AddTeamResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.team_team_get_with_http_info(x_vo_api_id, x_vo_api_key, team, **kwargs)
        else:
            (data) = self.team_team_get_with_http_info(x_vo_api_id, x_vo_api_key, team, **kwargs)
            return data

    def team_team_get_with_http_info(self, x_vo_api_id, x_vo_api_key, team, **kwargs):
        """
        Retrieve information for a team
        Get the information for the specified team.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_get_with_http_info(x_vo_api_id, x_vo_api_key, team, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to fetch (required)
        :return: AddTeamResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_vo_api_id', 'x_vo_api_key', 'team']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method team_team_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_vo_api_id' is set
        if ('x_vo_api_id' not in params) or (params['x_vo_api_id'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_id` when calling `team_team_get`")
        # verify the required parameter 'x_vo_api_key' is set
        if ('x_vo_api_key' not in params) or (params['x_vo_api_key'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_key` when calling `team_team_get`")
        # verify the required parameter 'team' is set
        if ('team' not in params) or (params['team'] is None):
            raise ValueError("Missing the required parameter `team` when calling `team_team_get`")


        collection_formats = {}

        resource_path = '/team/{team}'.replace('{format}', 'json')
        path_params = {}
        if 'team' in params:
            path_params['team'] = params['team']

        query_params = {}

        header_params = {}
        if 'x_vo_api_id' in params:
            header_params['X-VO-Api-Id'] = params['x_vo_api_id']
        if 'x_vo_api_key' in params:
            header_params['X-VO-Api-Key'] = params['x_vo_api_key']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='AddTeamResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def team_team_members_get(self, x_vo_api_id, x_vo_api_key, team, **kwargs):
        """
        Retrieve a list of members for a team
        Get the members for the specified team.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_members_get(x_vo_api_id, x_vo_api_key, team, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to fetch (required)
        :return: ListTeamMembersResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.team_team_members_get_with_http_info(x_vo_api_id, x_vo_api_key, team, **kwargs)
        else:
            (data) = self.team_team_members_get_with_http_info(x_vo_api_id, x_vo_api_key, team, **kwargs)
            return data

    def team_team_members_get_with_http_info(self, x_vo_api_id, x_vo_api_key, team, **kwargs):
        """
        Retrieve a list of members for a team
        Get the members for the specified team.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_members_get_with_http_info(x_vo_api_id, x_vo_api_key, team, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to fetch (required)
        :return: ListTeamMembersResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_vo_api_id', 'x_vo_api_key', 'team']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method team_team_members_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_vo_api_id' is set
        if ('x_vo_api_id' not in params) or (params['x_vo_api_id'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_id` when calling `team_team_members_get`")
        # verify the required parameter 'x_vo_api_key' is set
        if ('x_vo_api_key' not in params) or (params['x_vo_api_key'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_key` when calling `team_team_members_get`")
        # verify the required parameter 'team' is set
        if ('team' not in params) or (params['team'] is None):
            raise ValueError("Missing the required parameter `team` when calling `team_team_members_get`")


        collection_formats = {}

        resource_path = '/team/{team}/members'.replace('{format}', 'json')
        path_params = {}
        if 'team' in params:
            path_params['team'] = params['team']

        query_params = {}

        header_params = {}
        if 'x_vo_api_id' in params:
            header_params['X-VO-Api-Id'] = params['x_vo_api_id']
        if 'x_vo_api_key' in params:
            header_params['X-VO-Api-Key'] = params['x_vo_api_key']

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ListTeamMembersResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def team_team_members_post(self, x_vo_api_id, x_vo_api_key, team, body, **kwargs):
        """
        Add a team member
        Add a team member to your team.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_members_post(x_vo_api_id, x_vo_api_key, team, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to fetch (required)
        :param AddTeamMemberPayload body: (required)
        :return: ListTeamMembersResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.team_team_members_post_with_http_info(x_vo_api_id, x_vo_api_key, team, body, **kwargs)
        else:
            (data) = self.team_team_members_post_with_http_info(x_vo_api_id, x_vo_api_key, team, body, **kwargs)
            return data

    def team_team_members_post_with_http_info(self, x_vo_api_id, x_vo_api_key, team, body, **kwargs):
        """
        Add a team member
        Add a team member to your team.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_members_post_with_http_info(x_vo_api_id, x_vo_api_key, team, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to fetch (required)
        :param AddTeamMemberPayload body: (required)
        :return: ListTeamMembersResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_vo_api_id', 'x_vo_api_key', 'team', 'body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method team_team_members_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_vo_api_id' is set
        if ('x_vo_api_id' not in params) or (params['x_vo_api_id'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_id` when calling `team_team_members_post`")
        # verify the required parameter 'x_vo_api_key' is set
        if ('x_vo_api_key' not in params) or (params['x_vo_api_key'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_key` when calling `team_team_members_post`")
        # verify the required parameter 'team' is set
        if ('team' not in params) or (params['team'] is None):
            raise ValueError("Missing the required parameter `team` when calling `team_team_members_post`")
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `team_team_members_post`")


        collection_formats = {}

        resource_path = '/team/{team}/members'.replace('{format}', 'json')
        path_params = {}
        if 'team' in params:
            path_params['team'] = params['team']

        query_params = {}

        header_params = {}
        if 'x_vo_api_id' in params:
            header_params['X-VO-Api-Id'] = params['x_vo_api_id']
        if 'x_vo_api_key' in params:
            header_params['X-VO-Api-Key'] = params['x_vo_api_key']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ListTeamMembersResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def team_team_members_user_delete(self, x_vo_api_id, x_vo_api_key, team, user, body, **kwargs):
        """
        Remove a team member
        Remove a team from your organization.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_members_user_delete(x_vo_api_id, x_vo_api_key, team, user, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to be deleted (required)
        :param str user: The team member username (required)
        :param RemoveTeamMemberPayload body: The user information (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.team_team_members_user_delete_with_http_info(x_vo_api_id, x_vo_api_key, team, user, body, **kwargs)
        else:
            (data) = self.team_team_members_user_delete_with_http_info(x_vo_api_id, x_vo_api_key, team, user, body, **kwargs)
            return data

    def team_team_members_user_delete_with_http_info(self, x_vo_api_id, x_vo_api_key, team, user, body, **kwargs):
        """
        Remove a team member
        Remove a team from your organization.  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_members_user_delete_with_http_info(x_vo_api_id, x_vo_api_key, team, user, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to be deleted (required)
        :param str user: The team member username (required)
        :param RemoveTeamMemberPayload body: The user information (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_vo_api_id', 'x_vo_api_key', 'team', 'user', 'body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method team_team_members_user_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_vo_api_id' is set
        if ('x_vo_api_id' not in params) or (params['x_vo_api_id'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_id` when calling `team_team_members_user_delete`")
        # verify the required parameter 'x_vo_api_key' is set
        if ('x_vo_api_key' not in params) or (params['x_vo_api_key'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_key` when calling `team_team_members_user_delete`")
        # verify the required parameter 'team' is set
        if ('team' not in params) or (params['team'] is None):
            raise ValueError("Missing the required parameter `team` when calling `team_team_members_user_delete`")
        # verify the required parameter 'user' is set
        if ('user' not in params) or (params['user'] is None):
            raise ValueError("Missing the required parameter `user` when calling `team_team_members_user_delete`")
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `team_team_members_user_delete`")


        collection_formats = {}

        resource_path = '/team/{team}/members/{user}'.replace('{format}', 'json')
        path_params = {}
        if 'team' in params:
            path_params['team'] = params['team']
        if 'user' in params:
            path_params['user'] = params['user']

        query_params = {}

        header_params = {}
        if 'x_vo_api_id' in params:
            header_params['X-VO-Api-Id'] = params['x_vo_api_id']
        if 'x_vo_api_key' in params:
            header_params['X-VO-Api-Key'] = params['x_vo_api_key']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def team_team_put(self, x_vo_api_id, x_vo_api_key, team, body, **kwargs):
        """
        Update a team
        Update the designated team  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_put(x_vo_api_id, x_vo_api_key, team, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to be updated (required)
        :param AddTeamPayload body: The team information (required)
        :return: AddTeamResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.team_team_put_with_http_info(x_vo_api_id, x_vo_api_key, team, body, **kwargs)
        else:
            (data) = self.team_team_put_with_http_info(x_vo_api_id, x_vo_api_key, team, body, **kwargs)
            return data

    def team_team_put_with_http_info(self, x_vo_api_id, x_vo_api_key, team, body, **kwargs):
        """
        Update a team
        Update the designated team  This API may be called a maximum of 15 times per minute. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.team_team_put_with_http_info(x_vo_api_id, x_vo_api_key, team, body, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str x_vo_api_id: Your API ID (required)
        :param str x_vo_api_key: Your API Key (required)
        :param str team: The VictorOps team to be updated (required)
        :param AddTeamPayload body: The team information (required)
        :return: AddTeamResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['x_vo_api_id', 'x_vo_api_key', 'team', 'body']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method team_team_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'x_vo_api_id' is set
        if ('x_vo_api_id' not in params) or (params['x_vo_api_id'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_id` when calling `team_team_put`")
        # verify the required parameter 'x_vo_api_key' is set
        if ('x_vo_api_key' not in params) or (params['x_vo_api_key'] is None):
            raise ValueError("Missing the required parameter `x_vo_api_key` when calling `team_team_put`")
        # verify the required parameter 'team' is set
        if ('team' not in params) or (params['team'] is None):
            raise ValueError("Missing the required parameter `team` when calling `team_team_put`")
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `team_team_put`")


        collection_formats = {}

        resource_path = '/team/{team}'.replace('{format}', 'json')
        path_params = {}
        if 'team' in params:
            path_params['team'] = params['team']

        query_params = {}

        header_params = {}
        if 'x_vo_api_id' in params:
            header_params['X-VO-Api-Id'] = params['x_vo_api_id']
        if 'x_vo_api_key' in params:
            header_params['X-VO-Api-Key'] = params['x_vo_api_key']

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'PUT',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='AddTeamResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
